apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: carts-s1-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts-s1-primary
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: carts-s1-primary
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: carts-s1-canary
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/name: carts-s1-primary
        app.kubernetes.io/part-of: sockshop-approve
        app.kubernetes.io/version: 0.12.2
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: version=0.1.0 revision=1 releasename=sockshop-approve-staging-carts-s1
            keptn_project=sockshop-approve keptn_service=carts-s1 keptn_stage=staging
            keptn_deployment=primary
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['deployment']
        - name: CONTAINER_IMAGE
          value: docker.io/keptnexamples/carts:0.12.2
        - name: KEPTN_PROJECT
          value: carts-s1
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEPTN_SERVICE
          value: carts-s1
        - name: UNLEASH_SERVER_URL
          value: http://unleash.unleash-dev/api
        image: docker.io/keptnexamples/carts:0.12.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        name: carts-s1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
status: {}
