--- 
apiVersion: v1
kind: Service
metadata: 
  name: carts-s2
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    app: carts-s2
